### ISSUE TITLE
CSS `min()` not supported

### ISSUE THREAD

**Issue by ouroborus** [kiwibrowser/src#277]
I'm trying to use a computed css variable in a page as in:

```css
:root {
  --vw: 100vw;
  --vh: 100vh;
  --vmin: min(var(--vw), var(--vh));
}
```
In this example, `min(var(--vw), var(--vh))` is coming out as a string literal rather than being converted to pixels. This results in something like `width: var(--vmin)` setting a width of 0 pixels.

As far as I can tell, CSS functions aren't being processed when they're assigned to a variable.

Chrome mobile handles this scenario just fine, resulting in the correct pixel dimension.

Device: Samsung Galaxy S9+
OS: Android 10.0.0; SM-G965U Build/QP1A.190711.020
Kiwi: Git201216Gen426127039
Chrome: Chrome 87.0.4280.101
