### ISSUE TITLE
Fdroid or Github versions without google restrictions

### ISSUE THREAD

**Issue by SubhashBose** [kiwibrowser/src#388]
Until 2019 (I think), background playing for Youtube used to work in Kiwi browser. Then it got specifically restricted due to Google Play store policy / TOS. Since Kiwi is now fully open-source, it should have unrestricted versions available outside (in addition to) play store. Compiled apks can be made available through Github or F-Droid. 

A browser should be neutral towards all websites and no artificial restriction should be there for a specific website. If youtube can run in the background and picture-in-picture mode on desktop browsers, then there shouldn't be any browser-imposed restriction in Kiwi. This is also unfair for other video streaming websites like Vimeo, Dailymotion, etc, just because they don't have arm-twisting power like google. This is just my opinion and I believe a unique project like Kiwi should remain independent.

**Comment by kiwibrowser** [comment]
Hello,

Kiwi supports extensions and can load user scripts (.user.js) from any source and any file, so you are free to execute the JavaScript you want and decide how your browser should behave;
I think this is the beauty of Kiwi compared to Chrome and is an advantage in this situation if you want to change the default behaviour.

Regarding policy, Google has lot of ways to enforce them inside and outside of the Play Store, but I agree with you on the principle.

Kiwi has a special status with direct contact at Google (similar to large content creators and YouTube) so over time the relations between the two of us should improve and this will lead to interesting cases (e.g. improvement in Translate) that are worth it in the long-term I think.

**Comment by SubhashBose** [comment]
Hi,

Thanks for your reply. Yes, the ability for loading extensions is the only reason I use Kiwi, this opens up endless possibilities - injecting JS, blocking ads, modifying headers, and whatnot.  Otherwise, I am not really a fan of modded browsers. 

However, I am not entirely sure how Google can enforce restrictions outside the Play store for a specific browser. Kiwi doesn't even have its own UserAgent. The problem is with the out-of-box experience for an average user. Say, if I recommend this to someone, then I have to also thoroughly explain how to load external extensions/scripts. Not sure if it is a good idea, but maybe someone can try to maintain a forked branch with this restriction removed. 

Anyways, as you explained, it is completely understandable if Kiwi has commitments or a  built-up relationship with Google, which might yield some benefit in the long term. Then Kiwi should continue the way it is now.

**Comment by mutageneral** [comment]
@kiwibrowser, I do not have the play store on my phone. Can you please put this app on F-Droid? Even if it has the pointless restrictions I don't care, at least I will still be able to actually try out what's seems like a great web browser. I know I could sideload the APK, but a web browser is something important to keep up to date and I would clearly forget to update it and check the repo for new versions.

**Comment by mutageneral** [comment]
Also, putting it on F-Droid will bring even more users to this web browser who, like me, only have F-Droid and never heard of this web browser. I found out about this web browser because I happened to see it mentioned on a forum. If it had been on F-Droid, I would have known about it and tried it out a long time ago already. If you want more people discovering and using your app, you should put it on F-Droid!

**Comment by kiwibrowser** [comment]
I need to check if Kiwi Browser "classic" (src) is eligible to F-Droid, I think yes because it has fully transparent and reproducible builds (the builds is done on GitHub Actions).

**Comment by gcoda** [comment]
@kiwibrowser, maybe F-Droid custom repository could be a temporary solution? it wont bring more users, but will make updates possible without play store.

There is docker image for generating fdroid repo. Looks like it should be possible to make a github workflow out of it. I know nothing about fdroid, but from my brief "research"

```bash
# init one-time locally
docker run --rm -u $(id -u):$(id -g) -v $(pwd):/repo registry.gitlab.com/fdroid/docker-executable-fdroidserver:master init
```

generates:

- config.yml (edit name, icon, description, supports env references)
- keystore.p12 (should be stored in github workflow secrets?)

and something like this should work
```yaml
# .github/workflows
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # - name: somehow get artifacts
      #  uses: actions/download-artifact@v1

      # # fdroid fills "nativecode" property in index files for each detected APKs
      - name: copy APKs
        run: |
          cp apk-arm64/ChromeBrowser.apk repo/kiwibrowser-arm64.$GITHUB_SHA.apk
          cp apk-x86/ChromeBrowser.apk repo/kiwibrowser-x86.$GITHUB_SHA.apk

      # # somehow put config.yml and keystore.p12

      - name: update fdroid repo
        uses: docker://registry.gitlab.com/fdroid/docker-executable-fdroidserver:master
        with:
          entrypoint: /fdroidserver/fdroid # or /usr/local/bin/fdroid
          args: update # --create-metadata Add skeleton metadata files for APKs that are missing them

      # # repo/* can be uploaded to static hosting
```

- uploading and directly using S3 hosting probably needs "Website configuration API" support, so backblaze might not work.
- there is some notes about s3cfg and aws inside config.yml. Maybe it will keep links to old builds in index files
